// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkcvtenwmnlljymdzvvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrY3Z0ZW53bW5sbGp5bWR6dnZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTMzODMsImV4cCI6MjA3MjI4OTM4M30.a_4qByT8jeN746cL-TFjrIzAoz6vwDQ3l2SiSuo4Qcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});